
DOCUMENT=AEVO_Florian-Wilhelm


doc:
	pdflatex $(DOCUMENT).tex
	pdflatex $(DOCUMENT).tex
	pdflatex $(DOCUMENT).tex

clean:
	rm *aux *glg *glo *gls *ist *lof *log *out *toc *pyg

cleanall:
	rm *aux *glg *glo *gls *ist *lof *log *out *toc *pyg *pdf


