= Kotlin
Florian Wilhelm
1.0.0-SNAPSHOT

== What is Kotlin?

https://kotlinlang.org/[Kotlin] is a programming language for the JVM, developed by JetBrains.
It combines traits of the Java language with some of more modern ones, like Scala and Groovy.
Kotlin does not force any programming paradigm on you.
It is an object oriented language like Java and C#.
Functional programming is also a first class citizen, much more so then in Java 8.
In this respect, it resembles scala in some ways, but constraints itself to a more simple syntax.
For simple scripting tasks, an imperative approach is also possible, without the OO boilerplate that Java forces on you.
Kotlin's main target is the jvm, but there is also an (currently) experimental javascript backend available.
This enables you, to use one language for the backend and the frontend of you application, if you wish to do so.
Type inference is a feature that makes coding much more pleasant.
It is not unique to Kotlin, but it will be a nice thing to see for Java developers.
I mean, even C++ does have this to some extend

== Why use it?

=== Selling Points

* Concise

Java is too verbose.
Kotlin is here to fix that.

* Safe

> Get rid of those pesky NullPointerExceptions, you know, The Billion Dollar Mistake

* Versatile

** Existing Java Enterprise Apps
** Android
** JavaScript

* Interoperable

** Use all the Java Libraries that you know and like

=== Syntax Sugar

* `val` keyword for immutability
* heavy type inference -> `var` keyword for variables
* no `new` keyword for object creation -> less noise
* `data` classes -> "structs"
* String Templates -> `println("Hello, my name is ${name}")`
* Default Values for Parameters
* Raw Strings in triple quotes

----
val myText = """This is a very
important
message.
"""
----

* First Class Functions

----
fun timeSequential(x: Int): Int {
    return nX.eval(x) * nY.eval(x) * tA.eval(x) * numberOfOperations.eval(x)
}

val tS: Column = Column("Sequential Time", ::timeSequential)
----

Hope in the Java 6 wasteland of android
Null safety

=== Kotlin vs. X

==== Kotlin vs. Java

* Less verbose
* "Built in" Lombok
* JVM6 Bytecode with Java 8 Programming Model (Lambdas, ..)

==== Kotlin vs. Scala

* Less academic
* Closer to Java -> Less mental effort for Java Devs

==== Kotlin vs. Groovy

* Type-checks!


=== What does it have to offer for tarent?

* We are a Java shop -> We can use it in existing projects (as opposed to golang)
* Familiar syntax (kind of)

== How to use it?

You can try Kotlin out using the http://try.kotlinlang.org/[web-based editor].
Of course, you can download a standalone compiler, including the runtime jar.
IntelliJ IDEA includes a plugin for Kotlin.
There is also a plugin for Eclipse available, but I never tried it.

== Selected Projects using Kotlin

* https://github.com/cbeust/kobalt[Kobalt], a gradle-like build tool (Build files are nothing but Kotlin programs)
* https://github.com/fwilhe/Incell[Incell], my toy-spreadsheet application
* https://github.com/fwilhe/lab[lab], a work-in-progress gitlab auxillary application (like `hub` for github)
* https://github.com/jankotek/mapdb/tree/mapdb3[MapDB 3]

== Resources

* https://kotlinlang.org/
* https://kotlinlang.org/docs/kotlin-docs.pdf
* http://blog.omalley.id.au/2013/07/27/null-handling-in-kotlin.html
* https://medium.com/@octskyward/why-kotlin-is-my-next-programming-language-c25c001e26e3

