
DOCUMENT=Praesentation_Florian_Wilhelm


doc:
	pdflatex $(DOCUMENT).tex
	pdflatex $(DOCUMENT).tex
	pdflatex $(DOCUMENT).tex

clean:
	rm *aux *glg *glo *gls *ist *lof *log *out *toc *pyg *snm *nav

cleanall:
	rm *aux *glg *glo *gls *ist *lof *log *out *toc *pyg *snm *nav *pdf


